import globals from "globals";

export default [
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "src/renderer/vendor/**",
      "src/renderer/styles/vendor/**",
      "src/renderer/bundle.js",
      "assets/**",
      "**/*.min.js",
      "**/vendor/**",
    ],
  },
  {
    files: ["src/**/*.js", "tests/**/*.js", "index.js"],
    ignores: ["**/vendor/**", "**/*.min.js", "src/renderer/bundle.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
        app: "writable",
        tvKey: "writable",
        main: "writable",
        service: "writable",
        session: "writable",
        translate: "writable",
        languages: "writable",
        player: "writable",
        mapper: "writable",
        dashjs: "readonly",
        loading: "writable",
        exit: "writable",
        login: "writable",
        mylist: "writable",
        search: "writable",
        historyScreen: "writable",
        browse: "writable",
        profilesScreen: "writable",
        changelog: "writable",
        home: "writable",
        home_details: "writable",
        home_episodes: "writable",
        video: "writable",
        keyboard: "writable",
        menu: "writable",
        settings: "writable",
        electronUtilsRender: "readonly",
        tizen: "readonly",
        $: "readonly",
        jQuery: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-undef": "error",
      "no-var": "error",
      "prefer-const": "warn",
      eqeqeq: ["error", "smart"],
      curly: ["error", "multi-line"],
    },
  },
];
