name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "dev"
    tags:
      - "v*.*.*"

jobs:
  build_app:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: set git global safe directory
        run: |
          pacman -Syu git nodejs npm tree zip unzip --noconfirm
          git config --global --add safe.directory $(realpath .)

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and verify
        run: |
          npm ci --ignore-scripts || npm install --ignore-scripts
          npm run bundle
          npm test

      - name: Build AppImage
        run: |
          npm run build
          chmod +x dist/Crispyroll_v*_linux.AppImage

      - name: Build unpacked zip
        run: |
          npm run flatpak:build-unpacked
          zip -r dist/crispyroll_unpacked.zip dist/linux-unpacked

      - name: show files
        run: |
          ls ./dist/Crispyroll_v*_linux.AppImage
          ls ./dist/crispyroll_unpacked.zip

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: crispyroll-linux
          path: |
            ./dist/Crispyroll_v*_linux.AppImage
            ./dist/crispyroll_unpacked.zip

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build_app
    steps:
      - run: mkdir /tmp/artifacts

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts

      - run: ls -R /tmp/artifacts

      - name: publish to github release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/artifacts/crispyroll-linux/Crispyroll_v*_linux.AppImage
            /tmp/artifacts/crispyroll-linux/crispyroll_unpacked.zip
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: true
          prerelease: contains(github.ref, 'pre')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
